=== OrfeasZ/quickentity-editor-next/src/lib/schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/Entity",
	"definitions": {
		"Entity": {
			"type": "object",
			"properties": {
				"tempHash": {
					"type": "string"
				},
				"tbluHash": {
					"type": "string"
				},
				"rootEntity": {
					"type": "string"
				},
				"entities": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/SubEntity"
					}
				},
				"propertyOverrides": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/PropertyOverride"
					}
				},
				"overrideDeletes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Ref"
					}
				},
				"pinConnectionOverrides": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/PinConnectionOverride"
					}
				},
				"pinConnectionOverrideDeletes": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/PinConnectionOverrideDelete"
					}
				},
				"externalScenes": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"subType": {
					"$ref": "#/definitions/SubType"
				},
				"quickEntityVersion": {
					"type": "number"
				},
				"extraFactoryDependencies": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Dependency"
					}
				},
				"extraBlueprintDependencies": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Dependency"
					}
				},
				"comments": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/CommentEntity"
					}
				}
			},
			"required": [
				"tempHash",
				"tbluHash",
				"rootEntity",
				"entities",
				"propertyOverrides",
				"overrideDeletes",
				"pinConnectionOverrides",
				"pinConnectionOverrideDeletes",
				"externalScenes",
				"subType",
				"quickEntityVersion",
				"extraFactoryDependencies",
				"extraBlueprintDependencies",
				"comments"
			],
			"additionalProperties": false
		},
		"SubEntity": {
			"type": "object",
			"properties": {
				"parent": {
					"$ref": "#/definitions/Ref"
				},
				"name": {
					"type": "string"
				},
				"template": {
					"type": "string"
				},
				"templateFlag": {
					"type": "string",
					"default": "1F"
				},
				"blueprint": {
					"type": "string"
				},
				"editorOnly": {
					"type": "boolean",
					"default": false
				},
				"properties": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/Property"
					}
				},
				"platformSpecificProperties": {
					"type": "object",
					"additionalProperties": {
						"type": "object",
						"additionalProperties": {
							"$ref": "#/definitions/Property"
						}
					}
				},
				"events": {
					"type": "object",
					"additionalProperties": {
						"type": "object",
						"additionalProperties": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/RefMaybeConstantValue"
							}
						}
					}
				},
				"inputCopying": {
					"type": "object",
					"additionalProperties": {
						"type": "object",
						"additionalProperties": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/RefMaybeConstantValue"
							}
						}
					}
				},
				"outputCopying": {
					"type": "object",
					"additionalProperties": {
						"type": "object",
						"additionalProperties": {
							"type": "array",
							"items": {
								"$ref": "#/definitions/RefMaybeConstantValue"
							}
						}
					}
				},
				"propertyAliases": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/PropertyAlias"
					}
				},
				"exposedEntities": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/ExposedEntity"
					}
				},
				"exposedInterfaces": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
				"subsets": {
					"type": "object",
					"additionalProperties": {
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				}
			},
			"required": ["parent", "name", "template", "blueprint"],
			"additionalProperties": false,
			"default": {
				"parent": "fffffffffffffffe",
				"name": "New Entity",
				"template": "[modules:/zentity.class].pc_entitytype",
				"blueprint": "[modules:/zentity.class].pc_entityblueprint"
			}
		},
		"Ref": {
			"anyOf": [
				{
					"$ref": "#/definitions/FullRef"
				},
				{
					"type": "string"
				},
				{
					"type": "null"
				}
			]
		},
		"FullRef": {
			"type": "object",
			"properties": {
				"ref": {
					"type": "string"
				},
				"externalScene": {
					"type": ["string", "null"]
				},
				"exposedEntity": {
					"type": "string"
				}
			},
			"required": ["ref", "externalScene"],
			"additionalProperties": false
		},
		"Property": {
			"type": "object",
			"properties": {
				"type": {
					"type": "string"
				},
				"value": {},
				"postInit": {
					"type": "boolean",
					"default": false
				}
			},
			"required": ["type", "value"],
			"additionalProperties": false,
			"default": {
				"type": "",
				"value": ""
			}
		},
		"RefMaybeConstantValue": {
			"anyOf": [
				{
					"$ref": "#/definitions/RefWithConstantValue"
				},
				{
					"$ref": "#/definitions/Ref"
				}
			]
		},
		"RefWithConstantValue": {
			"type": "object",
			"properties": {
				"ref": {
					"$ref": "#/definitions/Ref"
				},
				"value": {
					"$ref": "#/definitions/SimpleProperty"
				}
			},
			"required": ["ref", "value"],
			"additionalProperties": false
		},
		"SimpleProperty": {
			"type": "object",
			"properties": {
				"type": {
					"type": "string"
				},
				"value": {}
			},
			"required": ["type", "value"],
			"additionalProperties": false
		},
		"PropertyAlias": {
			"type": "object",
			"properties": {
				"originalProperty": {
					"type": "string"
				},
				"originalEntity": {
					"$ref": "#/definitions/Ref"
				}
			},
			"required": ["originalProperty", "originalEntity"],
			"additionalProperties": false
		},
		"ExposedEntity": {
			"type": "object",
			"properties": {
				"isArray": {
					"type": "boolean"
				},
				"refersTo": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Ref"
					}
				}
			},
			"required": ["isArray", "refersTo"],
			"additionalProperties": false
		},
		"PropertyOverride": {
			"type": "object",
			"properties": {
				"entities": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/Ref"
					}
				},
				"properties": {
					"type": "object",
					"additionalProperties": {
						"$ref": "#/definitions/OverriddenProperty"
					}
				}
			},
			"required": ["entities", "properties"],
			"additionalProperties": false
		},
		"OverriddenProperty": {
			"type": "object",
			"properties": {
				"type": {
					"type": "string"
				},
				"value": {}
			},
			"required": ["type", "value"],
			"additionalProperties": false
		},
		"PinConnectionOverride": {
			"type": "object",
			"properties": {
				"fromEntity": {
					"$ref": "#/definitions/Ref"
				},
				"fromPin": {
					"type": "string"
				},
				"toEntity": {
					"$ref": "#/definitions/Ref"
				},
				"toPin": {
					"type": "string"
				},
				"value": {}
			},
			"required": ["fromEntity", "fromPin", "toEntity", "toPin"],
			"additionalProperties": false
		},
		"PinConnectionOverrideDelete": {
			"type": "object",
			"properties": {
				"fromEntity": {
					"$ref": "#/definitions/Ref"
				},
				"fromPin": {
					"type": "string"
				},
				"toEntity": {
					"$ref": "#/definitions/Ref"
				},
				"toPin": {
					"type": "string"
				},
				"value": {
					"$ref": "#/definitions/SimpleProperty"
				}
			},
			"required": ["fromEntity", "fromPin", "toEntity", "toPin"],
			"additionalProperties": false
		},
		"SubType": {
			"type": "string",
			"enum": ["brick", "scene", "template"]
		},
		"Dependency": {
			"anyOf": [
				{
					"$ref": "#/definitions/DependencyWithFlag"
				},
				{
					"type": "string"
				}
			]
		},
		"DependencyWithFlag": {
			"type": "object",
			"properties": {
				"resource": {
					"type": "string"
				},
				"flag": {
					"type": "string"
				}
			},
			"required": ["resource", "flag"],
			"additionalProperties": false
		},
		"CommentEntity": {
			"type": "object",
			"properties": {
				"parent": {
					"$ref": "#/definitions/Ref"
				},
				"name": {
					"type": "string"
				},
				"text": {
					"type": "string"
				}
			},
			"required": ["parent", "name", "text"],
			"additionalProperties": false
		}
	}
}

=== OrfeasZ/quickentity-editor-next/src-tauri/entity.json
{"tempHash":"0086A9F758D6E876","tbluHash":"00E0C6BE6AB47041","rootEntity":"fffffffffffffffe","entities":{"71c4074c4a8bbf7c":{"parent":"6a2ec361348c89b9","name":"ValueBool","template":"002155F39C60D3F0","blueprint":"00C162B1B6BF347C","properties":{"m_bValue":{"type":"bool","value":true}}},"5538c73c7f2525e":{"parent":"94e13e976fd76a98","name":"LD_AreaDiscoveredMapTracker","template":"00F16C5E709D6982","blueprint":"00E48DBCA95F0636","properties":{"m_pTextLine":{"type":"ZRuntimeResourceID","value":{"resource":"00930CDDD56C05D6","flag":"5F"}},"AreaDiscoveredBool":{"type":"TArray<SEntityTemplateReference>","value":["e3b6ece5c2a0e207"],"postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"94e13e976fd76a98","postInit":true}}},"1e20416670719cbb":{"parent":"a7baa24229561f17","name":"AreaDiscovered_Cinema","template":"00A0A2026E9090BC","blueprint":"00B09C0C1A885059","properties":{"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":0},"position":{"x":59.42510986328125,"y":156.90570068359375,"z":30.646820068359375}}},"m_eidParent":{"type":"SEntityTemplateReference","value":"fffffffffffffffe","postInit":true}}},"29a6ff6dd7d845f1":{"parent":"2a99a9370c1fd0c4","name":"OUTFITS_VILLAGE_SleepingMusician","template":"000F23BDD6485C73","blueprint":"00CEFA8569CAB6C0","properties":{"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":-4.892645088010187},"position":{"x":-84.2419662475586,"y":325.639892578125,"z":27.467859268188477}}},"Outfit_R_New_Id":{"type":"ZGuid","value":"bbc1dd7c-a0ef-41eb-9bef-a4c38fded3fa"},"Outfit_L_New_Id":{"type":"ZGuid","value":"cfacf46a-eb59-4a16-a221-a690defd05a3"},"Outfit_L_New_Id_1":{"type":"ZGuid","value":"ab5a46a2-6e53-4b15-a48e-c336df1ef5ff"},"Outfit_R_New_Id_1":{"type":"ZGuid","value":"57342129-03a9-47a4-a509-cc0656e0a76a"},"m_bVisible":{"type":"bool","value":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"fffffffffffffffe","postInit":true}},"subsets":{"AudioEmitters":["fffffffffffffffe"]}},"a06c10ceb948027":{"parent":"2a99a9370c1fd0c4","name":"GHOST_Shrine","template":"007BA33C78593593","blueprint":"00B5D563E788C21B","properties":{"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":-80.98767363439329},"position":{"x":-48.207149505615234,"y":261.5198974609375,"z":29.376310348510742}}},"m_rMainItemKeyl2":{"type":"SEntityTemplateReference","value":"da40b3289da00b2d","postInit":true},"m_rMainItemKeyr2":{"type":"SEntityTemplateReference","value":"d4cf424686913b36","postInit":true},"m_rMainItemKeyr1":{"type":"SEntityTemplateReference","value":"bb590cb2e1b0e7b9","postInit":true},"m_rMainItemKeyl1":{"type":"SEntityTemplateReference","value":"da40b3289da00b2d","postInit":true},"m_rMainItemKeyr3":{"type":"SEntityTemplateReference","value":"d4cf424686913b36","postInit":true},"m_rMainItemKeyl3":{"type":"SEntityTemplateReference","value":"da40b3289da00b2d","postInit":true},"m_rMainItemKeym1":{"type":"SEntityTemplateReference","value":"d02ed606ec4dc1b3","postInit":true},"m_rMainItemKeym2":{"type":"SEntityTemplateReference","value":"ac9acee6ae22447f","postInit":true},"m_rMainItemKeym3":{"type":"SEntityTemplateReference","value":"d02ed606ec4dc1b3","postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"fffffffffffffffe","postInit":true}},"subsets":{"AudioEmitters":["fffffffffffffffe"]}},"d562006eec025a8f":{"parent":"ff3eb5f3a50a0bf8","name":"ValueBool","template":"002155F39C60D3F0","blueprint":"00C162B1B6BF347C","properties":{"m_bValue":{"type":"bool","value":true}}},"a29ddc3f4ac645c4":{"parent":"a7baa24229561f17","name":"AreaDiscovered_Mansion_Gardens","template":"00A0A2026E9090BC","blueprint":"00B09C0C1A885059","properties":{"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":0},"position":{"x":63.0715217590332,"y":235.42559814453125,"z":32.62331008911133}}},"m_eidParent":{"type":"SEntityTemplateReference","value":"fffffffffffffffe","postInit":true}}},"fa095d3894a25ac0":{"parent":"a7baa24229561f17","name":"AreaDiscovered_Hippo_ConstructionOffice","template":"00A0A2026E9090BC","blueprint":"00B09C0C1A885059","properties":{"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":0},"position":{"x":90.6954116821289,"y":311.4971923828125,"z":21.33091926574707}}},"m_eidParent":{"type":"SEntityTemplateReference","value":"fffffffffffffffe","postInit":true}}},"1403fab90420585d":{"parent":"6e7c16b538bf22ea","name":"LD_AreaDiscoveredMapTracker","template":"00F16C5E709D6982","blueprint":"00E48DBCA95F0636","properties":{"m_pTextLine":{"type":"ZRuntimeResourceID","value":{"resource":"0033C72E42230587","flag":"5F"}},"AreaDiscoveredBool":{"type":"TArray<SEntityTemplateReference>","value":["118cdf8d28ba16c3"],"postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"6e7c16b538bf22ea","postInit":true}}},"68b0fc717aaef1dc":{"parent":"fc03d1ba859d328e","name":"Fire Extingusher","template":"0062AECA45FE019C","blueprint":"0093858240A45A2A","properties":{"m_RepositoryId":{"type":"ZGuid","value":"d64eb5f2-1e9b-402d-855b-c714cfde50db"}}},"b658285d43249e90":{"parent":"fc57d312187d66ec","name":"Pistol Magnum GOTY Striker","template":"0062AECA45FE019C","blueprint":"0093858240A45A2A","properties":{"m_RepositoryId":{"type":"ZGuid","value":"15291f69-88d0-4a8f-b31b-71605ba5ff38"}}},"64abd30f30dc07ce":{"parent":"ff3eb5f3a50a0bf8","name":"LD_AreaDiscoveredMapTracker","template":"00F16C5E709D6982","blueprint":"00E48DBCA95F0636","properties":{"m_pTextLine":{"type":"ZRuntimeResourceID","value":{"resource":"005356193553FE6B","flag":"5F"}},"AreaDiscoveredBool":{"type":"TArray<SEntityTemplateReference>","value":["d562006eec025a8f"],"postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"ff3eb5f3a50a0bf8","postInit":true}}},"b62fe6277723e606":{"parent":"6a2ec361348c89b9","name":"LD_AreaDiscoveredMapTracker","template":"00F16C5E709D6982","blueprint":"00E48DBCA95F0636","properties":{"m_pTextLine":{"type":"ZRuntimeResourceID","value":{"resource":"00AEEF6C58112715","flag":"5F"}},"AreaDiscoveredBool":{"type":"TArray<SEntityTemplateReference>","value":["71c4074c4a8bbf7c"],"postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"6a2ec361348c89b9","postInit":true}}},"d7e91ad8baccf4a8":{"parent":"b03fe6b95178326d","name":"LD_AreaDiscoveredMapTracker","template":"00F16C5E709D6982","blueprint":"00E48DBCA95F0636","properties":{"m_pTextLine":{"type":"ZRuntimeResourceID","value":{"resource":"005B04BD3666078C","flag":"5F"}},"AreaDiscoveredBool":{"type":"TArray<SEntityTemplateReference>","value":["52fe7709613525dd"],"postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"b03fe6b95178326d","postInit":true}}},"b573ca336b1881bf":{"parent":"67e706850f0c3e5a","name":"LD_AreaDiscoveredMapTracker","template":"00F16C5E709D6982","blueprint":"00E48DBCA95F0636","properties":{"m_pTextLine":{"type":"ZRuntimeResourceID","value":{"resource":"001F0D1A79F9ECC5","flag":"5F"}},"AreaDiscoveredBool":{"type":"TArray<SEntityTemplateReference>","value":["730538db29fffef7"],"postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"67e706850f0c3e5a","postInit":true}}},"b4d967c4b11ac0f8":{"parent":"2a1363182c57163c","name":"ValueBool","template":"002155F39C60D3F0","blueprint":"00C162B1B6BF347C","properties":{"m_bValue":{"type":"bool","value":true}}},"c6192486167030a0":{"parent":"2a99a9370c1fd0c4","name":"TOOLS_A_CocaTent","template":"007BA33C78593593","blueprint":"00B5D563E788C21B","properties":{"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":90.95780115348656},"position":{"x":69.00341033935547,"y":73.70929718017578,"z":30.601940155029297}}},"m_rMainItemKeyr3":{"type":"SEntityTemplateReference","value":"68b0fc717aaef1dc"},"m_rMainItemKeyl1":{"type":"SEntityTemplateReference","value":"c11f7ae6c3e9ad5c","postInit":true},"m_rMainItemKeyl2":{"type":"SEntityTemplateReference","value":"2f12793e47d9ba74","postInit":true},"m_rMainItemKeyl3":{"type":"SEntityTemplateReference","value":"94034800d5f288a9","postInit":true},"m_rMainItemKeym1":{"type":"SEntityTemplateReference","value":"27f3ce1d31b90044","postInit":true},"m_rMainItemKeym2":{"type":"SEntityTemplateReference","value":"7643a80b86e6a377","postInit":true},"m_rMainItemKeym3":{"type":"SEntityTemplateReference","value":"76a7eae504e70c54","postInit":true},"m_rMainItemKeyr1":{"type":"SEntityTemplateReference","value":"fa2041a4a6b8763e","postInit":true},"m_rMainItemKeyr2":{"type":"SEntityTemplateReference","value":"4cb91ec357a388b9","postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"fffffffffffffffe","postInit":true}},"subsets":{"AudioEmitters":["fffffffffffffffe"]}},"997579143ab94617":{"parent":"2a99a9370c1fd0c4","name":"TOOLS_A_BigScreen","template":"007BA33C78593593","blueprint":"00B5D563E788C21B","properties":{"m_mTransform":{"type":"SMatrix43","value":{"rotation":{"x":0,"y":0,"z":25.492133091702023},"position":{"x":54.09806823730469,"y":148.7303009033203,"z":31.6707706451416}}},"m_rMainItemKeyr3":{"type":"SEntityTemplateReference","value":"68b0fc717aaef1dc"},"m_rMainItemKeyl1":{"type":"SEntityTemplateReference","value":"c11f7ae6c3e9ad5c","postInit":true},"m_rMainItemKeyl2":{"type":"SEntityTemplateReference","value":"2f12793e47d9ba74","postInit":true},"m_rMainItemKeyl3":{"type":"SEntityTemplateReference","value":"94034800d5f288a9","postInit":true},"m_rMainItemKeym1":{"type":"SEntityTemplateReference","value":"27f3ce1d31b90044","postInit":true},"m_rMainItemKeym2":{"type":"SEntityTemplateReference","value":"7643a80b86e6a377","postInit":true},"m_rMainItemKeym3":{"type":"SEntityTemplateReference","value":"76a7eae504e70c54","postInit":true},"m_rMainItemKeyr1":{"type":"SEntityTemplateReference","value":"fa2041a4a6b8763e","postInit":true},"m_rMainItemKeyr2":{"type":"SEntityTemplateReference","value":"4cb91ec357a388b9","postInit":true},"m_eidParent":{"type":"SEntityTemplateReference","value":"fffffffffffffffe","postInit":true}},"subsets":{"AudioEmitters":["fffffffffffffffe
